name: Write release notes

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, closed, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  Release:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3


      - name: Create release notes 
        uses: release-drafter/release-drafter@v5
        with:
          commitish: main
          prerelease: false
          tag: ${{ env.RELEASE }}
          name: ${{ env.RELEASE }}
          version: ${{ env.RELEASE }}
          latest: true
