name: Release Everything

on:
  workflow_dispatch:
    # inputs:
    #   releaseVersion:
    #     description: 'The release version (e.g., 0.21.1)'
    #     required: true
    #     type: string
jobs:
  # print-version:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Show release version
  #       run: echo "Release version is ${{ github.event.inputs.releaseVersion }}"
  Release:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Set RELEASE env var from package.json
      #   run: echo RELEASE=$(node --print "require('./package.json').version") >> $GITHUB_ENV

      - name: check node version
        run: node -v
      - run: node ./.github/scripts/update-node-red-docker.js
      - name: Show release version
        run: echo "Release version is ${{ env.newVersion  }}"
      - name: Fail if tag already exists
        run: '! docker manifest inspect marwan17705/node-sample:${{ env.newVersion  }}'

      # - name: Set up Depot CLI
      #   uses: depot/setup-action@v1

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       marwan17705/node-sample:latest
      #       marwan17705/node-sample:10
# ${{ env.RELEASE }}
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push
      #   uses: depot/build-push-action@v1
      #   with:
      #     project: du7O4b0e8P
      #     token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
      #     context: .
      #     file: ./Dockerfile
      #     platforms: |
      #       linux/amd64
      #       linux/arm64
      #     push: true
      #     tags: |
      #       marwan17705/node-sample:${{ env.RELEASE }}
      #       marwan17705/node-sample:latest
      #       ghcr.io/marwan17705/node-sample:${{ env.RELEASE }}
      #       ghcr.io/marwan17705/node-sample:latest
